product-name: cf
product-properties:
  .cloud_controller.allow_app_ssh_access:
    value: true
  .cloud_controller.apps_domain:
    value: ((apps_domain))
  .cloud_controller.default_app_memory:
    value: 1024
  .cloud_controller.default_app_ssh_access:
    value: true
  .cloud_controller.default_disk_quota_app:
    value: 1024
  .cloud_controller.default_quota_max_number_services:
    value: 100
  .cloud_controller.default_quota_memory_limit_mb:
    value: 10240
  .cloud_controller.enable_custom_buildpacks:
    value: true
  .cloud_controller.encrypt_key:
    value: {}
  .cloud_controller.max_disk_quota_app:
    value: 2048
  .cloud_controller.max_file_size:
    value: 1024
  .cloud_controller.security_event_logging_enabled:
    value: true
  .cloud_controller.staging_timeout_in_seconds:
    value: 900
  .cloud_controller.system_domain:
    value: ((sys_domain))
  .diego_brain.starting_container_count_maximum:
    value: 200
  .doppler.message_drain_buffer_size:
    value: 10000
  .ha_proxy.skip_cert_verify:
    value: true
  .mysql.cli_history:
    value: true
  .mysql.max_connections:
    value: 3500
  .mysql.prevent_node_auto_rejoin:
    value: false
  .mysql.remote_admin_access:
    value: false
  .mysql_monitor.poll_frequency:
    value: 30
  .mysql_monitor.recipient_email:
    value: ((mysql_notification_email))
  .mysql_monitor.write_read_delay:
    value: 20
  .mysql_proxy.shutdown_delay:
    value: 30
  .mysql_proxy.startup_delay:
    value: 0
  .nfs_server.blobstore_internal_access_rules:
    value: allow 10.0.0.0/8;,allow 172.16.0.0/12;,allow 192.168.0.0/16;
  .properties.autoscale_api_disable_connection_pooling:
    value: false
  .properties.autoscale_api_instance_count:
    value: 1
  .properties.autoscale_enable_verbose_logging:
    value: false
  .properties.autoscale_instance_count:
    value: 3
  .properties.autoscale_metric_bucket_count:
    value: 120
  .properties.autoscale_scaling_interval_in_seconds:
    value: 35
  .properties.cc_api_rate_limit:
    value: disable
  .properties.cc_logging_level:
    value: info
  .properties.ccdb_connection_validation_timeout:
    value: 3600
  .properties.ccdb_read_timeout:
    value: 3600
  .properties.cf_networking_database_connection_timeout:
    value: 120
  .properties.cf_networking_enable_space_developer_self_service:
    value: false
  .properties.cf_networking_internal_domain:
    value: apps.internal
  .properties.cloud_controller_default_health_check_timeout:
    value: 60
  .properties.cloud_controller_default_stack:
    value: default
  .properties.cloud_controller_temporary_disable_deployments:
    value: false
  .properties.container_networking:
    value: enable
  .properties.container_networking_interface_plugin:
    value: silk
  .properties.container_networking_interface_plugin.silk.enable_log_traffic:
    value: false
  .properties.container_networking_interface_plugin.silk.iptables_accepted_udp_logs_per_sec:
    value: 100
  .properties.container_networking_interface_plugin.silk.iptables_denied_logs_per_sec:
    value: 1
  .properties.container_networking_interface_plugin.silk.network_mtu:
    value: 1454
  .properties.container_networking_interface_plugin.silk.vtep_port:
    value: 4789
  .properties.credhub_database:
    value: internal_mysql
  .properties.credhub_hsm_provider_client_certificate:
    value: {}
  .properties.credhub_hsm_provider_partition_password:
    value: {}
  .properties.credhub_key_encryption_passwords:
    value:
    - key:
        secret: ((credhub_encryption_secret))
      name: credhub-key
      primary: true
      provider: internal
  .properties.diego_database_max_open_connections:
    value: 100
  .properties.diego_log_timestamp_format:
    value: rfc3339
  .properties.enable_cf_metric_name:
    value: false
  .properties.enable_log_cache:
    value: true
  .properties.enable_smb_volume_driver:
    value: false
  .properties.enable_tls_to_internal_pxc:
    value: false
  .properties.experimental_dynamic_egress_enforcement:
    value: false
  .properties.garden_disk_cleanup:
    value: reserved
  .properties.gorouter_ssl_ciphers:
    value: ECDHE-RSA-AES128-GCM-SHA256:TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
  .properties.haproxy_client_cert_validation:
    value: none
  .properties.haproxy_forward_tls:
    value: disable
  .properties.haproxy_hsts_support:
    value: disable
  .properties.haproxy_max_buffer_size:
    value: 16384
  .properties.haproxy_ssl_ciphers:
    value: DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384
  .properties.locket_database_max_open_connections:
    value: 200
  .properties.metric_registrar_blacklisted_tags:
    value: deployment,job,index,id
  .properties.metric_registrar_enabled:
    value: false
  .properties.metric_registrar_scrape_interval_in_seconds:
    value: 35
  .properties.mysql_activity_logging:
    value: enable
  .properties.mysql_activity_logging.enable.audit_logging_events:
    value: connect,query
  .properties.networking_poe_ssl_certs:
    value:
    - certificate:
        cert_pem: ((ssl_cert))
        private_key_pem: ((ssl_key))
      name: pas-cert
  .properties.networkpolicyserver_database_max_open_connections:
    value: 200
  .properties.networkpolicyserverinternal_database_max_open_connections:
    value: 200
  .properties.nfs_volume_driver:
    value: disable
  .properties.push_apps_manager_app_poll_interval:
    value: 10
  .properties.push_apps_manager_company_name:
    value: Dragonfruit
  .properties.push_apps_manager_currency_lookup:
    value: '{ "usd": "$", "eur": "€" }'
  .properties.push_apps_manager_display_plan_prices:
    value: false
  .properties.push_apps_manager_enable_invitations:
    value: true
  .properties.push_apps_manager_poll_interval:
    value: 30
  .properties.route_integrity:
    value: tls_verify
  .properties.route_services:
    value: enable
  .properties.route_services.enable.ignore_ssl_cert_verification:
    value: false
  .properties.router_backend_max_conn:
    value: 500
  .properties.router_client_cert_validation:
    value: request
  .properties.router_enable_proxy:
    value: false
  .properties.router_keepalive_connections:
    value: enable
  .properties.routing_disable_http:
    value: false
  .properties.routing_log_client_ips:
    value: log_client_ips
  .properties.routing_minimum_tls_version:
    value: tls_v1_2
  .properties.routing_tls_termination:
    value: load_balancer
  .properties.saml_signature_algorithm:
    value: SHA256
  .properties.secure_service_instance_credentials:
    value: false
  .properties.security_acknowledgement:
    value: X
  .properties.silk_database_max_open_connections:
    value: 200
  .properties.smoke_tests:
    value: on_demand
  .properties.smtp_auth_mechanism:
    value: plain
  .properties.smtp_credentials:
    value: {}
  .properties.smtp_enable_starttls_auto:
    value: false
  .properties.syslog_drop_debug:
    value: true
  .properties.syslog_metrics_to_syslog_enabled:
    value: true
  .properties.syslog_tls:
    value: disabled
  .properties.syslog_use_tcp_for_file_forwarding_local_transport:
    value: false
  .properties.system_blobstore:
    value: external_gcs_service_account
  .properties.system_blobstore.external_gcs_service_account.buildpacks_bucket:
    value: ((buildpacks_bucket))
  .properties.system_blobstore.external_gcs_service_account.droplets_bucket:
    value: ((droplets_bucket))
  .properties.system_blobstore.external_gcs_service_account.packages_bucket:
    value: ((packages_bucket))
  .properties.system_blobstore.external_gcs_service_account.project_id:
    value: ((project))
  .properties.system_blobstore.external_gcs_service_account.resources_bucket:
    value: ((resources_bucket))
  .properties.system_blobstore.external_gcs_service_account.service_account_email:
    value: ((storage_service_account))
  .properties.system_blobstore.external_gcs_service_account.service_account_json_key:
    value: ((auth_json))
  .properties.system_blobstore_ccdroplet_max_staged_droplets_stored:
    value: 2
  .properties.system_blobstore_ccpackage_max_valid_packages_stored:
    value: 2
  .properties.system_database:
    value: external
  .properties.system_database.external.account_password:
    value:
      secret: ((sql_password))
  .properties.system_database.external.account_username:
    value: ((sql_username))
  .properties.system_database.external.app_usage_service_password:
    value:
      secret: ((sql_password))
  .properties.system_database.external.app_usage_service_username:
    value: ((sql_username))
  .properties.system_database.external.autoscale_password:
    value:
      secret: ((sql_password))
  .properties.system_database.external.autoscale_username:
    value: ((sql_username))
  .properties.system_database.external.ccdb_password:
    value:
      secret: ((sql_password))
  .properties.system_database.external.ccdb_username:
    value: ((sql_username))
  .properties.system_database.external.credhub_password:
    value:
      secret: ((sql_password))
  .properties.system_database.external.credhub_username:
    value: ((sql_username))
  .properties.system_database.external.diego_password:
    value:
      secret: ((sql_password))
  .properties.system_database.external.diego_username:
    value: ((sql_username))
  .properties.system_database.external.host:
    value: ((sql_host))
  .properties.system_database.external.locket_password:
    value:
      secret: ((sql_password))
  .properties.system_database.external.locket_username:
    value: ((sql_username))
  .properties.system_database.external.networkpolicyserver_password:
    value:
      secret: ((sql_password))
  .properties.system_database.external.networkpolicyserver_username:
    value: ((sql_username))
  .properties.system_database.external.nfsvolume_password:
    value:
      secret: ((sql_password))
  .properties.system_database.external.nfsvolume_username:
    value: ((sql_username))
  .properties.system_database.external.notifications_password:
    value:
      secret: ((sql_password))
  .properties.system_database.external.notifications_username:
    value: ((sql_username))
  .properties.system_database.external.port:
    value: 3306
  .properties.system_database.external.routing_password:
    value:
      secret: ((sql_password))
  .properties.system_database.external.routing_username:
    value: ((sql_username))
  .properties.system_database.external.silk_password:
    value:
      secret: ((sql_password))
  .properties.system_database.external.silk_username:
    value: ((sql_username))
  .properties.system_database.external.uaa_password:
    value:
      secret: ((sql_password))
  .properties.system_database.external.uaa_username:
    value: ((sql_username))
  .properties.tcp_routing:
    value: disable
  .properties.uaa:
    value: internal
  .properties.uaa.internal.password_expires_after_months:
    value: 0
  .properties.uaa.internal.password_max_retry:
    value: 5
  .properties.uaa.internal.password_min_length:
    value: 0
  .properties.uaa.internal.password_min_lowercase:
    value: 0
  .properties.uaa.internal.password_min_numeric:
    value: 0
  .properties.uaa.internal.password_min_special:
    value: 0
  .properties.uaa.internal.password_min_uppercase:
    value: 0
  .properties.uaa_database:
    value: internal_mysql
  .properties.uaa_session_cookie_max_age:
    value: 28800
  .properties.uaa_session_idle_timeout:
    value: 1800
  .router.disable_insecure_cookies:
    value: false
  .router.drain_wait:
    value: 20
  .router.enable_isolated_routing:
    value: false
  .router.enable_write_access_logs:
    value: true
  .router.enable_zipkin:
    value: true
  .router.frontend_idle_timeout:
    value: 900
  .router.lb_healthy_threshold:
    value: 20
  .router.request_timeout_in_seconds:
    value: 900
  .uaa.apps_manager_access_token_lifetime:
    value: 3600
  .uaa.apps_manager_refresh_token_lifetime:
    value: 3600
  .uaa.cf_cli_access_token_lifetime:
    value: 7200
  .uaa.cf_cli_refresh_token_lifetime:
    value: 1209600
  .uaa.customize_password_label:
    value: Password
  .uaa.customize_username_label:
    value: Email
  .uaa.proxy_ips_regex:
    value: 10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|169\.254\.\d{1,3}\.\d{1,3}|127\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.1[6-9]{1}\.\d{1,3}\.\d{1,3}|172\.2[0-9]{1}\.\d{1,3}\.\d{1,3}|172\.3[0-1]{1}\.\d{1,3}\.\d{1,3}
  .uaa.service_provider_key_credentials:
    value:
      cert_pem: ((ssl_cert))
      private_key_pem: ((ssl_key))
  .uaa.service_provider_key_password:
    value: {}
network-properties:
  network:
    name: ((network_name))
  other_availability_zones:
  - name: us-west1-a
  - name: us-west1-b
  - name: us-west1-c
  singleton_availability_zone:
    name: us-west1-a
resource-config:
  backup_restore:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
    internet_connected: true
  clock_global:
    instances: 1
    instance_type:
      id: automatic
    internet_connected: true
  cloud_controller:
    instances: 1
    instance_type:
      id: automatic
    internet_connected: true
  cloud_controller_worker:
    instances: 1
    instance_type:
      id: automatic
    internet_connected: true
  credhub:
    instances: 1
    instance_type:
      id: automatic
    internet_connected: true
  diego_brain:
    instances: 1
    instance_type:
      id: automatic
    internet_connected: true
    elb_names:
    - tcp:((ssh_router_pool))
  diego_cell:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: true
  diego_database:
    instances: 1
    instance_type:
      id: automatic
    internet_connected: true
  doppler:
    instances: 1
    instance_type:
      id: automatic
    internet_connected: true
  ha_proxy:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: true
  loggregator_trafficcontroller:
    instances: 1
    instance_type:
      id: automatic
    internet_connected: true
  mysql:
    instances: 0
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
    internet_connected: true
  mysql_monitor:
    instances: 0
    instance_type:
      id: automatic
    internet_connected: true
  mysql_proxy:
    instances: 0
    instance_type:
      id: automatic
    internet_connected: true
  nats:
    instances: 1
    instance_type:
      id: automatic
    internet_connected: true
  nfs_server:
    instances: 0
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
    internet_connected: true
  router:
    instances: 1
    instance_type:
      id: automatic
    internet_connected: true
    elb_names:
    - tcp:((ws_router_pool))
    - http:((http_lb_backend_name))
  syslog_adapter:
    instances: 1
    instance_type:
      id: automatic
    internet_connected: true
  syslog_scheduler:
    instances: 1
    instance_type:
      id: automatic
    internet_connected: true
  tcp_router:
    instances: 0
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
    internet_connected: true
  uaa:
    instances: 1
    instance_type:
      id: automatic
    internet_connected: true
errand-config:
  deploy-autoscaler:
    post-deploy-state: true
  deploy-notifications:
    post-deploy-state: false
  deploy-notifications-ui:
    post-deploy-state: false
  metric_registrar_smoke_test:
    post-deploy-state: false
  nfsbrokerpush:
    post-deploy-state: true
  push-apps-manager:
    post-deploy-state: true
  push-usage-service:
    post-deploy-state: true
  smbbrokerpush:
    post-deploy-state: false
  smoke_tests:
    post-deploy-state: true
  test-autoscaling:
    post-deploy-state: true

