az-configuration:
- name: us-west-1b
- name: us-west-1c
network-assignment:
  network:
    name: infrastructure
  other_availability_zones: []
  singleton_availability_zone:
    name: us-west-1b
networks-configuration:
  icmp_checks_enabled: false
  networks:
  - name: infrastructure
    subnets:
    - iaas_identifier: ((infrastructure_subnet_b))
      cidr: 10.0.16.0/28
      dns: 10.0.0.2
      gateway: 10.0.16.1
      reserved_ip_ranges: 10.0.16.0-10.0.16.4
      availability_zone_names:
      - us-west-1b
    - iaas_identifier: ((infrastructure_subnet_c))
      cidr: 10.0.16.16/28
      dns: 10.0.0.2
      gateway: 10.0.16.17
      reserved_ip_ranges: 10.0.16.16-10.0.16.20
      availability_zone_names:
      - us-west-1c
  - name: control-plane
    subnets:
    - iaas_identifier: ((control_plane_subnet_b))
      cidr: 10.0.4.0/26
      dns: 10.0.0.1
      gateway: 10.0.4.1
      reserved_ip_ranges: 10.0.4.1-10.0.4.10
      availability_zone_names:
      - us-west-1b
    - iaas_identifier: ((control_plane_subnet_c))
      cidr: 10.0.4.64/26
      dns: 10.0.0.1
      gateway: 10.0.4.65
      reserved_ip_ranges: 10.0.4.64-10.0.4.73
      availability_zone_names:
      - us-west-1c
properties-configuration:
  director_configuration:
    allow_legacy_agents: true
    blobstore_type: local
    bosh_recreate_on_next_deploy: true
    bosh_recreate_persistent_disks_on_next_deploy: true
    database_type: internal
    director_worker_count: 5
    encryption:
      keys: []
      providers: []
    hm_emailer_options:
      enabled: false
    hm_pager_duty_options:
      enabled: false
    identification_tags: {}
    keep_unreachable_vms: false
    local_blobstore_options:
      tls_enabled: true
    ntp_servers_string: 0.amazon.pool.ntp.org, 1.amazon.pool.ntp.org, 2.amazon.pool.ntp.org,
      3.amazon.pool.ntp.org
    post_deploy_enabled: true
    resurrector_enabled: true
    retry_bosh_deploys: true
    skip_director_drain: true
  dns_configuration:
    excluded_recursors: []
    handlers: []
  iaas_configuration:
    additional_cloud_properties: {}
    encrypted: false
    key_pair_name: ((env_name))-ops-manager-key
    name: default
    region: us-west-1
    security_group: ((security_group))
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    ssh_private_key: ((ssh_private_key))
  security_configuration:
    generate_vm_passwords: true
    opsmanager_root_ca_trusted_certs: false
  syslog_configuration:
    enabled: false
resource-configuration:
  compilation:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: false
  director:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
    internet_connected: false
vmextensions-configuration: []

